"""
Quick Email Templates for SDG 7 Alert System
Pre-made templates for different alert types
"""


class EmailTemplates:
    """Quick email templates for different alert scenarios"""
    
    @staticmethod
    def urgent_alert(country, access, year):
        """🚨 Urgent Alert Template"""
        subject = f"🚨 URGENT: Immediate Action Required - Electricity Access Crisis in {country}"
        
        body = f"""
URGENT ALERT - IMMEDIATE ACTION REQUIRED

Country: {country}
Current Electricity Access: {access:.1f}%
Year: {year}
Status: CRITICAL

⚠️ SITUATION ANALYSIS:
Your country's electricity access rate of {access:.1f}% is critically below the SDG 7 target.
This requires immediate intervention to prevent further deterioration.

🚨 IMMEDIATE ACTIONS REQUIRED:
1. Declare energy emergency and mobilize resources
2. Fast-track renewable energy projects
3. Seek international aid and partnerships
4. Implement emergency rural electrification
5. Establish crisis management team

💰 FUNDING OPPORTUNITIES:
- World Bank Energy Access Fund
- UN Sustainable Energy for All Initiative
- Green Climate Fund
- Regional Development Banks

📞 CONTACT FOR SUPPORT:
SDG 7 Monitoring System
Email: support@sdg7alerts.org

This is an automated alert generated by ML predictions.
        """
        
        return subject, body
    
    @staticmethod
    def reminder(country, access, year):
        """📢 Reminder Template"""
        subject = f"📢 Reminder: Action Needed to Improve Electricity Access in {country}"
        
        body = f"""
REMINDER - ACTION RECOMMENDED

Country: {country}
Current Electricity Access: {access:.1f}%
Year: {year}
Status: NEEDS IMPROVEMENT

📊 CURRENT SITUATION:
Your country's electricity access rate of {access:.1f}% shows room for improvement
to meet SDG 7 targets by 2030.

💡 RECOMMENDED ACTIONS:
1. Expand grid infrastructure to underserved areas
2. Invest in off-grid renewable solutions
3. Strengthen energy policy frameworks
4. Increase budget allocation for energy sector
5. Partner with private sector for investments

📈 SUCCESS EXAMPLES:
- Rwanda: Increased access from 23% to 47% in 5 years
- Bangladesh: Rural electrification program success
- Kenya: Off-grid solar revolution

🎯 NEXT STEPS:
Review and update your national energy strategy
Set quarterly milestones for improvement

This is an automated reminder from SDG 7 Monitoring System.
        """
        
        return subject, body
    
    @staticmethod
    def congratulations(country, access, year):
        """🎉 Congratulations Template"""
        subject = f"🎉 Congratulations! {country} Achieves Excellent Electricity Access"
        
        body = f"""
CONGRATULATIONS - EXCELLENT ACHIEVEMENT!

Country: {country}
Current Electricity Access: {access:.1f}%
Year: {year}
Status: EXCELLENT

🎉 OUTSTANDING PERFORMANCE:
Congratulations! Your country has achieved an excellent electricity access rate
of {access:.1f}%, demonstrating strong commitment to SDG 7.

⭐ ACHIEVEMENTS RECOGNIZED:
- Universal electricity access nearly achieved
- Strong infrastructure development
- Effective energy policies
- Sustainable energy transition

🌟 RECOMMENDATIONS FOR CONTINUED SUCCESS:
1. Maintain and upgrade existing infrastructure
2. Focus on renewable energy expansion
3. Share best practices with other nations
4. Support regional energy cooperation
5. Invest in smart grid technologies

🏆 LEADERSHIP OPPORTUNITY:
Your success can inspire other nations. Consider:
- Hosting regional energy conferences
- Providing technical assistance to neighbors
- Sharing policy frameworks and lessons learned

Keep up the excellent work!

SDG 7 Monitoring System
        """
        
        return subject, body
    
    @staticmethod
    def status_update(country, access, year):
        """📊 Status Update Template"""
        subject = f"📊 Status Update: Electricity Access Progress in {country}"
        
        body = f"""
STATUS UPDATE - PROGRESS REPORT

Country: {country}
Current Electricity Access: {access:.1f}%
Year: {year}
Status: ON TRACK

📊 CURRENT STATUS:
Your country's electricity access rate of {access:.1f}% shows steady progress
toward SDG 7 targets.

✅ POSITIVE INDICATORS:
- Access rate above 75%
- Steady improvement trend
- Good infrastructure foundation

💡 OPPORTUNITIES FOR ENHANCEMENT:
1. Accelerate rural electrification programs
2. Increase renewable energy share
3. Improve grid reliability and quality
4. Reduce energy poverty in remote areas
5. Enhance energy efficiency measures

📈 BENCHMARKING:
- Regional Average: Compare with neighbors
- SDG 7 Target: Universal access by 2030
- Best Practices: Learn from top performers

🎯 RECOMMENDED FOCUS AREAS:
- Last-mile connectivity
- Quality and reliability improvements
- Sustainable energy transition
- Affordability for low-income households

Continue your good progress!

SDG 7 Monitoring System
        """
        
        return subject, body
    
    @staticmethod
    def get_template_by_type(template_type, country, access, year):
        """
        Get email template by type
        
        Args:
            template_type: 'urgent', 'reminder', 'congratulations', or 'status_update'
            country: Country name
            access: Electricity access percentage
            year: Year
            
        Returns:
            tuple: (subject, body)
        """
        templates = {
            'urgent': EmailTemplates.urgent_alert,
            'reminder': EmailTemplates.reminder,
            'congratulations': EmailTemplates.congratulations,
            'status_update': EmailTemplates.status_update
        }
        
        template_func = templates.get(template_type, EmailTemplates.status_update)
        return template_func(country, access, year)
    
    @staticmethod
    def get_all_template_types():
        """Get list of all available template types"""
        return [
            {'id': 'urgent', 'name': 'Urgent Alert', 'icon': '🚨', 'color': 'danger'},
            {'id': 'reminder', 'name': 'Reminder', 'icon': '📢', 'color': 'warning'},
            {'id': 'congratulations', 'name': 'Congratulations', 'icon': '🎉', 'color': 'success'},
            {'id': 'status_update', 'name': 'Status Update', 'icon': '📊', 'color': 'info'}
        ]
